# Generated by Django 6.0.7 on 2026-07-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('shrimp_species', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_from', models.PositiveIntegerField()),
                ('day_to', models.PositiveIntegerField()),
                ('recommended_quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feeding_time', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='crops.crop')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crops.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_type', models.CharField(choices=[('PARTIAL', 'Partial'), ('FINAL', 'Final')], max_length=20)),
                ('harvest_date', models.DateField()),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_weight_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='crops.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pond_type', models.CharField(choices=[('GROW', 'Grow Pond'), ('WATER', 'Water Reservoir')], max_length=20)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('record_mode', models.CharField(choices=[('OFF', 'Off'), ('ALERT', 'Alert Only'), ('ALL', 'Record All')], default='ALERT', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='crops.farm')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='crops.pond'),
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='crops.crop')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='crops.pond')),
            ],
        ),
        migrations.CreateModel(
            name='Stocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocking_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('average_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocking', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='WaterExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PUMP_IN', 'Pump In'), ('SIPHON', 'Siphon')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exchange_time', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_exchanges', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('treatment_time', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_treatments', to='crops.crop')),
            ],
        ),
    ]
