# Generated by Django 6.0.7 on 2026-07-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='expected_harvest_date',
            field=models.DateField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='recommended_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pond',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pond',
            name='depth_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pond_type',
            field=models.CharField(choices=[('GROW', 'Grow Pond'), ('WATER', 'Water Reservoir')], default='GROW', max_length=20),
        ),
        migrations.AlterField(
            model_name='pond',
            name='record_mode',
            field=models.CharField(choices=[('OFF', 'Off'), ('ALERT', 'Alert Only'), ('ALL', 'Record All')], default='OFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='average_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
